require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - lib/generators/**/templates/**/*
    - gemfiles/**/*
    - vendor/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - 'spec/view_component/**/*'
    - 'spec/internal/db/schema.rb'
