plugins:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'gemfiles/**/*'
    - 'lib/generators/**/templates/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - 'spec/view_component/**/*'
    - 'spec/internal/db/schema.rb'
